version: '3.8'

services:
  judge-node-1:
    image: devassess/judge-service:latest
    container_name: judge-node-1
    env_file:
      - .env
    environment:
      - JUDGE_WORK_DIR=/host_mnt/d/KMA_Docs/Final_KMA/source_code/oj-sandbox/work-dir
      - JUDGE_CACHE_DIR=/host_mnt/d/KMA_Docs/Final_KMA/source_code/oj-sandbox/testcases-cache
      - MINIO_HOST=host.docker.internal
      - RABBITMQ_HOST=host.docker.internal
      - DOCKER_HOST=tcp://host.docker.internal:2375
      - SPRING_RABBITMQ_LISTENER_SIMPLE_PREFETCH=1
      - JUDGE_CONTAINER_NO_NEW_PRIVILEGES=true
      - JUDGE_CONTAINER_SECCOMP_PROFILE=
    volumes:
      - D:\KMA_Docs\Final_KMA\source_code\oj-sandbox\work-dir:/host_mnt/d/KMA_Docs/Final_KMA/source_code/oj-sandbox/work-dir
      - D:\KMA_Docs\Final_KMA\source_code\oj-sandbox\testcases-cache:/host_mnt/d/KMA_Docs/Final_KMA/source_code/oj-sandbox/testcases-cache
      - D:\KMA_Docs\Final_KMA\source_code\judge-service\seccomp:/host_mnt/d/KMA_Docs/Final_KMA/source_code/judge-service/seccomp:ro
    network_mode: "bridge"

  judge-node-2:
    image: devassess/judge-service:latest
    container_name: judge-node-2
    env_file:
      - .env
    environment:
      - JUDGE_WORK_DIR=/host_mnt/d/KMA_Docs/Final_KMA/source_code/oj-sandbox/work-dir
      - JUDGE_CACHE_DIR=/host_mnt/d/KMA_Docs/Final_KMA/source_code/oj-sandbox/testcases-cache
      - MINIO_HOST=host.docker.internal
      - RABBITMQ_HOST=host.docker.internal
      - DOCKER_HOST=tcp://host.docker.internal:2375
      - SPRING_RABBITMQ_LISTENER_SIMPLE_PREFETCH=1
      - JUDGE_CONTAINER_NO_NEW_PRIVILEGES=true
      - JUDGE_CONTAINER_SECCOMP_PROFILE=
    volumes:
      - D:\KMA_Docs\Final_KMA\source_code\oj-sandbox\work-dir:/host_mnt/d/KMA_Docs/Final_KMA/source_code/oj-sandbox/work-dir
      - D:\KMA_Docs\Final_KMA\source_code\oj-sandbox\testcases-cache:/host_mnt/d/KMA_Docs/Final_KMA/source_code/oj-sandbox/testcases-cache
      - D:\KMA_Docs\Final_KMA\source_code\judge-service\seccomp:/host_mnt/d/KMA_Docs/Final_KMA/source_code/judge-service/seccomp:ro
    network_mode: "bridge"
